#3) Create a Python program that uses turtles, 
# loops and has at least one user-defined function in it to help draw things. 
# It is up to you what the program will do (draw). 

import turtle
t = turtle.Turtle()
t.speed(4)

def main():
    mapleleaf()
    shape()
    logo()

def mapleleaf():
    t.pencolor("red")
    t.pensize(3)
    t.begin_fill()
    t.left(90)
    t.down()
    t.forward(60)
    t.right(100)
    t.down()
    t.forward(60)
    t.left(120)
    t.down()
    t.forward(30)
    t.right(70)
    t.down()
    t.forward(70)
    t.left(120)
    t.down()
    t.forward(20)
    t.right(85)
    t.down()
    t.forward(40)
    t.left(120)
    t.down()
    t.forward(40)
    t.right(80)
    t.down()
    t.forward(20)
    t.left(110)
    t.down()
    t.forward(50)
    t.right(140)
    t.down()
    t.forward(70)
    t.left(125)
    t.down()
    t.forward(20)
    t.right(90)
    t.down()
    t.forward(40)
    t.left(125)
    t.down()
    t.forward(40)
    t.right(90)
    t.down()
    t.forward(20)
    t.left(130)
    t.down()
    t.forward(70)
    t.right(145)
    t.down()
    t.forward(50)
    t.left(110) 
    t.down()
    t.forward(20)
    t.right(80) 
    t.down()
    t.forward(40)
    t.left(120)
    t.down()
    t.forward(40)
    t.right(80)
    t.down()
    t.forward(20)
    t.left(120)
    t.down()
    t.forward(70)
    t.right(60)
    t.down()
    t.forward(30)
    t.left(105)
    t.down()
    t.forward(50)
    t.right(100)
    t.down()
    t.forward(60)
    t.left(90)
    t.down()
    t.forward(8)
    t.end_fill()

def shape():
    count = 0
    while count < 2:
        t.forward(100)
        t.left(90)
        t.forward(40)
        t.left(90)
        count = count + 1

def logo():
     t.pencolor("black")
     t.pensize(2)
     t.left(90)
     t.up()
     t.forward(10)
     t.right(90)
     t.up()
     t.forward(10)
     t.down()
     t.forward(20)
     t.left(90)
     t.up()
     t.forward(20)
     t.left(90)
     t.down()
     t.forward(20)
     t.left(90)
     t.down()
     t.forward(20)
     t.left(90)
     t.up()
     t.forward(25)
     t.left(90)
     t.down()
     t.forward(20)
     t.right(150)
     t.down()
     t.forward(15)
     t.left(130)
     t.down()
     t.forward(15)
     t.right(150)
     t.down()
     t.forward(20)
     t.left(80)
     t.up()
     t.forward(5)
     t.down()
     t.forward(20)
     t.left(180)
     t.up()
     t.forward(20)
     t.right(90)
     t.down()
     t.forward(10)
     t.right(90)
     t.down()
     t.forward(20)
     t.left(90)
     t.down()
     t.forward(10)
     t.left(90)
     t.down()
     t.forward(20)
     t.right(180)
     t.up()
     t.forward(25)
     t.down()
     t.forward(10)
     t.right(90)
     t.down()
     t.forward(20)
     t.right(90)
     t.down()
     t.forward(10)
     t.right(90)
     t.down()
     t.forward(20)

main()
input()



